### ISSUE TITLE
Install cilk

### ISSUE THREAD

**Issue by joancf** [yushangdi/parChain#2]
Hi,
Your package looks great, but I was not able to install/run it.
Do you have more information on how to install cilk:
Which version do you use (is the intel version? which one?) or is it open cilk? 
Maybe, there is a docker with c++ and cilk already installed. Do you know if this option exists?
I found this one
https://github.com/jonniesweb/docker-cilkplus/blob/master/Dockerfile
but seems that the gcc is 5.4, maybe too old ;-( 

Thanks!!!
Joan

**Comment by yushangdi** [comment]
Hi Joan,

Sorry I do not have more information on how to install cilk. I was running on AWS Ubuntu machines, which have CILK installed by default.

I am writing a version of ParChain that does not rely on CILK: https://github.com/yushangdi/ParChain-HAC
Instead of CILK, it uses parlay (https://github.com/cmuparlay/parlaylib) for parallelism.

The code has not been thoroughly tested, and is under development, but I’ve tested it on some small datasets and it is correct on them.
I hope this is helpful.

**Comment by joancf** [comment]
Thanks for answering,
I can try on AWS,  but I managed to run it on my linux Mint 20.04 , with the difference that I'm using gcc and g++ 6.0 instead of 7.5 to have cilk running.

I did this setup
```
sudo vim /etc/apt/sources.list
add "deb http://dk.archive.ubuntu.com/ubuntu/ bionic main universe" to file
sudo apt update
sudo apt-get install gcc-6 g++-6 -y
sudo apt-get install lib32cilkrts5 libcilkrts5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 6
sudo update-alternatives --install /usr/bin/g++ g++ /usr/local/bin/g++ 11
sudo update-alternatives --config g++
export PATH=/usr/bin/:$PATH
```
I had to change the path because /usr/local/bin was before /usr/bin
and now seems to be working.
